[project]
name = "estate-dues-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Onyedika Christopher", email = "cosimon.tech@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
estate-dues-tracker = "estate_dues_tracker:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
